# Schema for the configuration files of the wwm_devel module.

wwm_devel.settings:
  type: config_object
  label: 'WWM Devel Settings'
  mapping:
    maintenance_mode:
      type: integer
      label: 'Maintenance mode'
    mailchimp_api_setting:
      type: string
      label: MailChimp API Key Setting
    mailchimp_api_key:
      type: string
      label: MailChimp API Key (backup)
